# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import messages_pb2 as proto_dot_messages__pb2


class HubStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateUser = channel.unary_unary(
        '/hub.rpc.Hub/CreateUser',
        request_serializer=proto_dot_messages__pb2.CreateUserRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.CreateUserReply.FromString,
        )
    self.GetBalance = channel.unary_unary(
        '/hub.rpc.Hub/GetBalance',
        request_serializer=proto_dot_messages__pb2.GetBalanceRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.GetBalanceReply.FromString,
        )
    self.GetDepositAddress = channel.unary_unary(
        '/hub.rpc.Hub/GetDepositAddress',
        request_serializer=proto_dot_messages__pb2.GetDepositAddressRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.GetDepositAddressReply.FromString,
        )
    self.UserWithdraw = channel.unary_unary(
        '/hub.rpc.Hub/UserWithdraw',
        request_serializer=proto_dot_messages__pb2.UserWithdrawRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.UserWithdrawReply.FromString,
        )
    self.UserWithdrawCancel = channel.unary_unary(
        '/hub.rpc.Hub/UserWithdrawCancel',
        request_serializer=proto_dot_messages__pb2.UserWithdrawCancelRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.UserWithdrawCancelReply.FromString,
        )
    self.GetUserHistory = channel.unary_unary(
        '/hub.rpc.Hub/GetUserHistory',
        request_serializer=proto_dot_messages__pb2.GetUserHistoryRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.GetUserHistoryReply.FromString,
        )
    self.ProcessTransferBatch = channel.unary_unary(
        '/hub.rpc.Hub/ProcessTransferBatch',
        request_serializer=proto_dot_messages__pb2.ProcessTransferBatchRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.ProcessTransferBatchReply.FromString,
        )
    self.BalanceSubscription = channel.unary_stream(
        '/hub.rpc.Hub/BalanceSubscription',
        request_serializer=proto_dot_messages__pb2.BalanceSubscriptionRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.BalanceEvent.FromString,
        )
    self.GetStats = channel.unary_unary(
        '/hub.rpc.Hub/GetStats',
        request_serializer=proto_dot_messages__pb2.StatsRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.StatsReply.FromString,
        )
    self.SweepSubscription = channel.unary_stream(
        '/hub.rpc.Hub/SweepSubscription',
        request_serializer=proto_dot_messages__pb2.SweepSubscriptionRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.SweepEvent.FromString,
        )
    self.GetAddressInfo = channel.unary_unary(
        '/hub.rpc.Hub/GetAddressInfo',
        request_serializer=proto_dot_messages__pb2.GetAddressInfoRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.GetAddressInfoReply.FromString,
        )
    self.SweepInfo = channel.unary_unary(
        '/hub.rpc.Hub/SweepInfo',
        request_serializer=proto_dot_messages__pb2.SweepInfoRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.SweepEvent.FromString,
        )
    self.SignBundle = channel.unary_unary(
        '/hub.rpc.Hub/SignBundle',
        request_serializer=proto_dot_messages__pb2.SignBundleRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.SignBundleReply.FromString,
        )
    self.SweepDetail = channel.unary_unary(
        '/hub.rpc.Hub/SweepDetail',
        request_serializer=proto_dot_messages__pb2.SweepDetailRequest.SerializeToString,
        response_deserializer=proto_dot_messages__pb2.SweepDetailReply.FromString,
        )


class HubServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateUser(self, request, context):
    """Creates a new user on the Hub
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBalance(self, request, context):
    """Returns the available balance for a user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDepositAddress(self, request, context):
    """Creates a new deposit address for a user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserWithdraw(self, request, context):
    """Submits a withdrawal request for a user.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserWithdrawCancel(self, request, context):
    """Attempts to cancel a user's withdrawal request.
    Only possible as long as sweep hasn't started yet.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserHistory(self, request, context):
    """Returns a user's full balance change history as recorded by the Hub
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProcessTransferBatch(self, request, context):
    """Processes a batch of buys/sells from the exchange
    Note that the amounts of this batch must sum to 0!
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BalanceSubscription(self, request, context):
    """Produces a stream of all balance changes as they appear since the provided timestamp
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStats(self, request, context):
    """Provides statistics about the Hub
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SweepSubscription(self, request, context):
    """Produces a stream of all sweeps since the provided timestamp
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAddressInfo(self, request, context):
    """Provides information on an address if it's owned by the Hub
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SweepInfo(self, request, context):
    """Provides information on the sweep for the given withdrawal or bundle hash
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SignBundle(self, request, context):
    """Provides a signature for a bundle hash
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SweepDetail(self, request, context):
    """Provides detailed information on the sweep for the bundle hash
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HubServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=proto_dot_messages__pb2.CreateUserRequest.FromString,
          response_serializer=proto_dot_messages__pb2.CreateUserReply.SerializeToString,
      ),
      'GetBalance': grpc.unary_unary_rpc_method_handler(
          servicer.GetBalance,
          request_deserializer=proto_dot_messages__pb2.GetBalanceRequest.FromString,
          response_serializer=proto_dot_messages__pb2.GetBalanceReply.SerializeToString,
      ),
      'GetDepositAddress': grpc.unary_unary_rpc_method_handler(
          servicer.GetDepositAddress,
          request_deserializer=proto_dot_messages__pb2.GetDepositAddressRequest.FromString,
          response_serializer=proto_dot_messages__pb2.GetDepositAddressReply.SerializeToString,
      ),
      'UserWithdraw': grpc.unary_unary_rpc_method_handler(
          servicer.UserWithdraw,
          request_deserializer=proto_dot_messages__pb2.UserWithdrawRequest.FromString,
          response_serializer=proto_dot_messages__pb2.UserWithdrawReply.SerializeToString,
      ),
      'UserWithdrawCancel': grpc.unary_unary_rpc_method_handler(
          servicer.UserWithdrawCancel,
          request_deserializer=proto_dot_messages__pb2.UserWithdrawCancelRequest.FromString,
          response_serializer=proto_dot_messages__pb2.UserWithdrawCancelReply.SerializeToString,
      ),
      'GetUserHistory': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserHistory,
          request_deserializer=proto_dot_messages__pb2.GetUserHistoryRequest.FromString,
          response_serializer=proto_dot_messages__pb2.GetUserHistoryReply.SerializeToString,
      ),
      'ProcessTransferBatch': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessTransferBatch,
          request_deserializer=proto_dot_messages__pb2.ProcessTransferBatchRequest.FromString,
          response_serializer=proto_dot_messages__pb2.ProcessTransferBatchReply.SerializeToString,
      ),
      'BalanceSubscription': grpc.unary_stream_rpc_method_handler(
          servicer.BalanceSubscription,
          request_deserializer=proto_dot_messages__pb2.BalanceSubscriptionRequest.FromString,
          response_serializer=proto_dot_messages__pb2.BalanceEvent.SerializeToString,
      ),
      'GetStats': grpc.unary_unary_rpc_method_handler(
          servicer.GetStats,
          request_deserializer=proto_dot_messages__pb2.StatsRequest.FromString,
          response_serializer=proto_dot_messages__pb2.StatsReply.SerializeToString,
      ),
      'SweepSubscription': grpc.unary_stream_rpc_method_handler(
          servicer.SweepSubscription,
          request_deserializer=proto_dot_messages__pb2.SweepSubscriptionRequest.FromString,
          response_serializer=proto_dot_messages__pb2.SweepEvent.SerializeToString,
      ),
      'GetAddressInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetAddressInfo,
          request_deserializer=proto_dot_messages__pb2.GetAddressInfoRequest.FromString,
          response_serializer=proto_dot_messages__pb2.GetAddressInfoReply.SerializeToString,
      ),
      'SweepInfo': grpc.unary_unary_rpc_method_handler(
          servicer.SweepInfo,
          request_deserializer=proto_dot_messages__pb2.SweepInfoRequest.FromString,
          response_serializer=proto_dot_messages__pb2.SweepEvent.SerializeToString,
      ),
      'SignBundle': grpc.unary_unary_rpc_method_handler(
          servicer.SignBundle,
          request_deserializer=proto_dot_messages__pb2.SignBundleRequest.FromString,
          response_serializer=proto_dot_messages__pb2.SignBundleReply.SerializeToString,
      ),
      'SweepDetail': grpc.unary_unary_rpc_method_handler(
          servicer.SweepDetail,
          request_deserializer=proto_dot_messages__pb2.SweepDetailRequest.FromString,
          response_serializer=proto_dot_messages__pb2.SweepDetailReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hub.rpc.Hub', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
