# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hub.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import messages_pb2 as proto_dot_messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/hub.proto',
  package='hub.rpc',
  syntax='proto3',
  serialized_options=_b('\n\017org.iota.rpchub'),
  serialized_pb=_b('\n\x0fproto/hub.proto\x12\x07hub.rpc\x1a\x14proto/messages.proto2\xb2\x08\n\x03Hub\x12\x42\n\nCreateUser\x12\x1a.hub.rpc.CreateUserRequest\x1a\x18.hub.rpc.CreateUserReply\x12\x42\n\nGetBalance\x12\x1a.hub.rpc.GetBalanceRequest\x1a\x18.hub.rpc.GetBalanceReply\x12W\n\x11GetDepositAddress\x12!.hub.rpc.GetDepositAddressRequest\x1a\x1f.hub.rpc.GetDepositAddressReply\x12H\n\x0cUserWithdraw\x12\x1c.hub.rpc.UserWithdrawRequest\x1a\x1a.hub.rpc.UserWithdrawReply\x12Z\n\x12UserWithdrawCancel\x12\".hub.rpc.UserWithdrawCancelRequest\x1a .hub.rpc.UserWithdrawCancelReply\x12N\n\x0eGetUserHistory\x12\x1e.hub.rpc.GetUserHistoryRequest\x1a\x1c.hub.rpc.GetUserHistoryReply\x12`\n\x14ProcessTransferBatch\x12$.hub.rpc.ProcessTransferBatchRequest\x1a\".hub.rpc.ProcessTransferBatchReply\x12S\n\x13\x42\x61lanceSubscription\x12#.hub.rpc.BalanceSubscriptionRequest\x1a\x15.hub.rpc.BalanceEvent0\x01\x12\x36\n\x08GetStats\x12\x15.hub.rpc.StatsRequest\x1a\x13.hub.rpc.StatsReply\x12M\n\x11SweepSubscription\x12!.hub.rpc.SweepSubscriptionRequest\x1a\x13.hub.rpc.SweepEvent0\x01\x12N\n\x0eGetAddressInfo\x12\x1e.hub.rpc.GetAddressInfoRequest\x1a\x1c.hub.rpc.GetAddressInfoReply\x12;\n\tSweepInfo\x12\x19.hub.rpc.SweepInfoRequest\x1a\x13.hub.rpc.SweepEvent\x12\x42\n\nSignBundle\x12\x1a.hub.rpc.SignBundleRequest\x1a\x18.hub.rpc.SignBundleReply\x12\x45\n\x0bSweepDetail\x12\x1b.hub.rpc.SweepDetailRequest\x1a\x19.hub.rpc.SweepDetailReplyB\x11\n\x0forg.iota.rpchubb\x06proto3')
  ,
  dependencies=[proto_dot_messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_HUB = _descriptor.ServiceDescriptor(
  name='Hub',
  full_name='hub.rpc.Hub',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=51,
  serialized_end=1125,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateUser',
    full_name='hub.rpc.Hub.CreateUser',
    index=0,
    containing_service=None,
    input_type=proto_dot_messages__pb2._CREATEUSERREQUEST,
    output_type=proto_dot_messages__pb2._CREATEUSERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBalance',
    full_name='hub.rpc.Hub.GetBalance',
    index=1,
    containing_service=None,
    input_type=proto_dot_messages__pb2._GETBALANCEREQUEST,
    output_type=proto_dot_messages__pb2._GETBALANCEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDepositAddress',
    full_name='hub.rpc.Hub.GetDepositAddress',
    index=2,
    containing_service=None,
    input_type=proto_dot_messages__pb2._GETDEPOSITADDRESSREQUEST,
    output_type=proto_dot_messages__pb2._GETDEPOSITADDRESSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UserWithdraw',
    full_name='hub.rpc.Hub.UserWithdraw',
    index=3,
    containing_service=None,
    input_type=proto_dot_messages__pb2._USERWITHDRAWREQUEST,
    output_type=proto_dot_messages__pb2._USERWITHDRAWREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UserWithdrawCancel',
    full_name='hub.rpc.Hub.UserWithdrawCancel',
    index=4,
    containing_service=None,
    input_type=proto_dot_messages__pb2._USERWITHDRAWCANCELREQUEST,
    output_type=proto_dot_messages__pb2._USERWITHDRAWCANCELREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserHistory',
    full_name='hub.rpc.Hub.GetUserHistory',
    index=5,
    containing_service=None,
    input_type=proto_dot_messages__pb2._GETUSERHISTORYREQUEST,
    output_type=proto_dot_messages__pb2._GETUSERHISTORYREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ProcessTransferBatch',
    full_name='hub.rpc.Hub.ProcessTransferBatch',
    index=6,
    containing_service=None,
    input_type=proto_dot_messages__pb2._PROCESSTRANSFERBATCHREQUEST,
    output_type=proto_dot_messages__pb2._PROCESSTRANSFERBATCHREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BalanceSubscription',
    full_name='hub.rpc.Hub.BalanceSubscription',
    index=7,
    containing_service=None,
    input_type=proto_dot_messages__pb2._BALANCESUBSCRIPTIONREQUEST,
    output_type=proto_dot_messages__pb2._BALANCEEVENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStats',
    full_name='hub.rpc.Hub.GetStats',
    index=8,
    containing_service=None,
    input_type=proto_dot_messages__pb2._STATSREQUEST,
    output_type=proto_dot_messages__pb2._STATSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SweepSubscription',
    full_name='hub.rpc.Hub.SweepSubscription',
    index=9,
    containing_service=None,
    input_type=proto_dot_messages__pb2._SWEEPSUBSCRIPTIONREQUEST,
    output_type=proto_dot_messages__pb2._SWEEPEVENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAddressInfo',
    full_name='hub.rpc.Hub.GetAddressInfo',
    index=10,
    containing_service=None,
    input_type=proto_dot_messages__pb2._GETADDRESSINFOREQUEST,
    output_type=proto_dot_messages__pb2._GETADDRESSINFOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SweepInfo',
    full_name='hub.rpc.Hub.SweepInfo',
    index=11,
    containing_service=None,
    input_type=proto_dot_messages__pb2._SWEEPINFOREQUEST,
    output_type=proto_dot_messages__pb2._SWEEPEVENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SignBundle',
    full_name='hub.rpc.Hub.SignBundle',
    index=12,
    containing_service=None,
    input_type=proto_dot_messages__pb2._SIGNBUNDLEREQUEST,
    output_type=proto_dot_messages__pb2._SIGNBUNDLEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SweepDetail',
    full_name='hub.rpc.Hub.SweepDetail',
    index=13,
    containing_service=None,
    input_type=proto_dot_messages__pb2._SWEEPDETAILREQUEST,
    output_type=proto_dot_messages__pb2._SWEEPDETAILREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HUB)

DESCRIPTOR.services_by_name['Hub'] = _HUB

# @@protoc_insertion_point(module_scope)
